/**
 * @fileoverview Android Reviewer Agent
 * @description Validates Kotlin/Android implementation and creates GitHub PR
 */

import { BaseAgent } from '../base';
import { AgentContext, AgentResult } from '../../types';
import { runGradleTests, runAndroidLint, verifyAndroidEnvironment } from '../../tools/gradle-runner';
import { initGit, createGitHubPR, addJiraComment, getModifiedFiles } from '../../tools/git';
import * as path from 'path';

/**
 * AndroidReviewerAgent: Validates Android implementation and creates GitHub PR
 * 
 * Uses gradle testDebugUnitTest + lintDebug for validation.
 */
export class AndroidReviewerAgent extends BaseAgent {
  name = 'AndroidReviewer';

  async execute(context: AgentContext): Promise<AgentResult> {
    const { job, workspacePath } = context;
    const repoPath = path.join(workspacePath, 'repo');
    
    this.log(`Reviewing Android implementation for: ${job.title}`);
    
    try {
      // 1. Verify Android environment
      const env = await verifyAndroidEnvironment(repoPath);
      if (!env.valid) {
        return { success: false, output: '', error: `Android environment invalid: ${env.errors.join(', ')}` };
      }
      
      // 2. Run Android Lint
      this.log('Running Android lint...');
      const lintResult = await runAndroidLint(repoPath, job.module);
      if (!lintResult.passed) {
        return {
          success: false,
          output: lintResult.stdout,
          error: `Android lint failed: ${lintResult.stderr}`,
          testResults: [lintResult],
        };
      }
      
      // 3. Run tests
      this.log('Running gradle tests...');
      const testResult = await runGradleTests(repoPath, job.module);
      if (!testResult.passed) {
        return {
          success: false,
          output: testResult.stdout,
          error: `Gradle tests failed: ${testResult.stderr}`,
          testResults: [testResult],
        };
      }
      
      // 4. Verify file count
      const git = initGit(repoPath);
      const modifiedFiles = await getModifiedFiles(git);
      if (modifiedFiles.length > job.maxFilesToTouch) {
        return { success: false, output: '', error: `Too many files modified: ${modifiedFiles.length} > ${job.maxFilesToTouch}` };
      }
      
      // 5. Verify spec exists
      if (!job.spec) {
        return { success: false, output: '', error: 'No spec found for traceability verification' };
      }
      
      // 6. Create GitHub PR
      this.log('Creating GitHub PR...');
      const pr = await createGitHubPR({
        owner: process.env.GITHUB_OWNER || 'rappi',
        repo: job.repo,
        title: `[${job.jiraTicketId || 'GAIA'}] ${job.title}`,
        body: this.generatePRBody(job),
        head: job.branchName || 'feature-branch',
        base: job.targetBranch,
      });
      
      this.log(`Created PR: ${pr.url}`);
      
      // 7. Comment on Jira
      if (job.jiraTicketId) {
        this.log(`Adding comment to Jira ticket ${job.jiraTicketId}...`);
        await addJiraComment(job.jiraTicketId, `Pull Request created: ${pr.url}`);
      }
      
      return {
        success: true,
        output: `Android review passed. PR created: ${pr.url}`,
        prUrl: pr.url,
        prId: pr.id,
      };
    } catch (error) {
      return { success: false, output: '', error: `Android review failed: ${error}` };
    }
  }

  private generatePRBody(job: AgentContext['job']): string {
    if (!job.spec) return '';
    
    const requirements = job.spec.requirements.map(r => `- [x] ${r.content}`).join('\n');
    const design = job.spec.design;
    
    return `## ${job.title}

**Jira:** ${job.jiraTicketId || 'N/A'}
**Platform:** Android (Kotlin)

### Requirements
${requirements}

### Changes
**Modified files:**
${design.affectedFiles.map(f => `- \`${f}\``).join('\n')}

**New files:**
${design.newFiles.map(f => `- \`${f}\` (created)`).join('\n')}

### Design Decisions
${design.architectureDecisions.map(d => `- ${d}`).join('\n')}

### Verification
- [x] All unit tests passing
- [x] Android lint clean
- [x] Files within limit (${job.maxFilesToTouch})
- [x] Traceability to spec verified

---
*Generated by Gaia Code Harness 🤖*`;
  }
}
