/**
 * @fileoverview Reviewer Agent
 * @description Validates implementation and creates GitHub PR
 */

import { BaseAgent } from './base';
import { AgentContext, AgentResult } from '../types';
import { runFlutterTests, runDartAnalyze, verifyFlutterEnvironment } from '../tools/test-runner';
import { initGit, createGitHubPR, addJiraComment, getModifiedFiles } from '../tools/git';
import * as path from 'path';

/**
 * ReviewerAgent: Validates implementation and creates GitHub PR
 * 
 * Input: Job with implemented code
 * Output: Validation result, PR URL
 */
export class ReviewerAgent extends BaseAgent {
  name = 'Reviewer';

  async execute(context: AgentContext): Promise<AgentResult> {
    const { job, workspacePath } = context;
    const repoPath = path.join(workspacePath, 'repo');
    
    this.log(`Reviewing implementation for: ${job.title}`);
    
    try {
      // 1. Verify Flutter environment
      const env = await verifyFlutterEnvironment(repoPath);
      if (!env.valid) {
        return {
          success: false,
          output: '',
          error: `Flutter environment invalid: ${env.errors.join(', ')}`,
        };
      }
      
      // 2. Run dart analyze
      this.log('Running dart analyze...');
      const analyzeResult = await runDartAnalyze(repoPath);
      if (!analyzeResult.passed) {
        return {
          success: false,
          output: analyzeResult.stdout,
          error: `Dart analyze failed: ${analyzeResult.stderr}`,
          testResults: [analyzeResult],
        };
      }
      
      // 3. Run tests
      this.log('Running tests...');
      const testResult = await runFlutterTests({
        workingDir: repoPath,
        module: job.module,
      });
      
      if (!testResult.passed) {
        return {
          success: false,
          output: testResult.stdout,
          error: `Tests failed: ${testResult.stderr}`,
          testResults: [testResult],
        };
      }
      
      // 4. Verify number of files changed
      const git = initGit(repoPath);
      const modifiedFiles = await getModifiedFiles(git);
      
      if (modifiedFiles.length > job.maxFilesToTouch) {
        return {
          success: false,
          output: '',
          error: `Too many files modified: ${modifiedFiles.length} > ${job.maxFilesToTouch}`,
        };
      }
      
      // 5. Verify traceability with spec
      if (!job.spec) {
        return {
          success: false,
          output: '',
          error: 'No spec found for traceability verification',
        };
      }
      
      // 6. Create GitHub PR
      this.log('Creating GitHub PR...');
      const pr = await createGitHubPR({
        owner: process.env.GITHUB_OWNER || 'rappi',
        repo: job.repo,
        title: `[${job.jiraTicketId || 'GAIA'}] ${job.title}`,
        body: this.generatePRBody(job),
        head: job.branchName || 'feature-branch',
        base: job.targetBranch,
      });
      
      this.log(`Created PR: ${pr.url}`);
      
      // 7. Comment on Jira if ticket exists
      if (job.jiraTicketId) {
        this.log(`Adding comment to Jira ticket ${job.jiraTicketId}...`);
        await addJiraComment(job.jiraTicketId, `Pull Request created: ${pr.url}`);
      }
      
      return {
        success: true,
        output: `Review passed. PR created: ${pr.url}`,
        prUrl: pr.url,
        prId: pr.id,
      };
      
    } catch (error) {
      return {
        success: false,
        output: '',
        error: `Review failed: ${error}`,
      };
    }
  }

  private generatePRBody(job: AgentContext['job']): string {
    if (!job.spec) return '';
    
    const requirements = job.spec.requirements
      .map(r => `- [x] ${r.content}`)
      .join('\n');
    
    const design = job.spec.design;
    
    return `## ${job.title}

**Jira:** ${job.jiraTicketId || 'N/A'}

### Requirements
${requirements}

### Changes
**Modified files:**
${design.affectedFiles.map(f => `- \`${f}\``).join('\n')}

**New files:**
${design.newFiles.map(f => `- \`${f}\` (created)`).join('\n')}

### Design Decisions
${design.architectureDecisions.map(d => `- ${d}`).join('\n')}

### Verification
- [x] All tests passing
- [x] Dart analyze clean
- [x] Files within limit (${job.maxFilesToTouch})
- [x] Traceability to spec verified

---
*Generated by Gaia Code Harness 🤖*`;
  }
}
